import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import localFont from "next/font/local";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
})

const intrudingCat = localFont(
  {
    src: [
      {
        path: "../../public/fonts/IntrudingCat.ttf",
        weight: "300",
        style: "normal",
      },
      {
        path: "../../public/fonts/IntrudingCat.otf",
        weight: "300",
        style: "normal",
      },
    ],
    variable: "--font-intruding-cat",
    display: "swap",
  }
)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${intrudingCat.variable}`}>
        {children}
      </body>
    </html>
  );
}
